export const oakData = [
  {
    name: "Commis",
    location: "3859 Piedmont Ave",
    yelpRating: 4.5,
    website: "https://www.commisrestaurant.com/",
  },
  {
    name: "Battambang",
    location: "850 Broadway",
    yelpRating: 4.5,
    website: "http://battambangrestaurant.net/",
  },
  {
    name: "Homeroom",
    location: "400 40th St",
    yelpRating: 4.5,
    website: "https://homeroom510.com/",
  },
  {
    name: "Champa Garden",
    location: "2102 8th Ave",
    yelpRating: 4.5,
    website: "https://www.champagarden.com/",
  },
  {
    name: "Zachary's Chicago Pizza",
    location: "5801 College Ave",
    yelpRating: 4.5,
    website: "https://zacharys.com/",
  },
  {
    name: "Pizzaiolo",
    location: "5008 Telegraph Ave",
    yelpRating: 4.5,
    website: "http://www.pizzaiolooakland.com/",
  },
  {
    name: "The Wolf",
    location: "3853 Piedmont Ave",
    yelpRating: 4.5,
    website: "https://www.thewolfoakland.com/",
  },
  {
    name: "Shan Dong",
    location: "328 10th St",
    yelpRating: 4.5,
    website: "http://shandongoakland.com/",
  },
  {
    name: "Shakewell",
    location: "3407 Lakeshore Ave",
    yelpRating: 4.5,
    website: "https://www.shakewelloakland.com/",
  },
  {
    name: "Hopscotch",
    location: "1915 San Pablo Ave",
    yelpRating: 4.5,
    website: "https://hopscotchoakland.com/",
  },
  {
    name: "Mua",
    location: "2442a Webster St",
    yelpRating: 4.5,
    website: "https://www.muaoakland.com/",
  },
  {
    name: "A16",
    location: "5356 College Ave",
    yelpRating: 4.5,
    website: "https://a16pizza.com/",
  },
  {
    name: "Brown Sugar Kitchen",
    location: "2295 Broadway",
    yelpRating: 4.5,
    website: "https://www.brownsugarkitchen.com/",
  },
  {
    name: "Grand Lake Kitchen",
    location: "576 Grand Ave",
    yelpRating: 4.5,
    website: "https://www.grandlakekitchen.com/",
  },
  {
    name: "Cafe Colucci",
    location: "6427 Telegraph Ave",
    yelpRating: 4.5,
    website: "https://www.cafecolucci.com/",
  },
  {
    name: "Burma Superstar",
    location: "4721 Telegraph Ave",
    yelpRating: 4.5,
    website: "http://www.burmasuperstar.com/",
  },
  {
    name: "Souley Vegan",
    location: "301 Broadway",
    yelpRating: 4.5,
    website: "https://www.souleyvegan.com/",
  },
  {
    name: "Kingston 11 Cuisine",
    location: "2270 Telegraph Ave",
    yelpRating: 4.5,
    website: "https://kingston11eats.com/",
  },
  {
    name: "Bakesale Betty",
    location: "5098 Telegraph Ave",
    yelpRating: 4.5,
    website: "http://www.bakesalebetty.com/",
  },
  {
    name: "Juhu Beach Club",
    location: "5179 Telegraph Ave",
    yelpRating: 4.5,
    website: "https://www.juhubeachclub.com/",
  },
  {
    name: "Cafe Van Kleef",
    location: "1621 Telegraph Ave",
    yelpRating: 4.5,
    website: "https://www.cafevankleef.com/",
  },
  {
    name: "Geta",
    location: "165 41st St",
    yelpRating: 4.5,
    website: "https://getasushi.com/",
  },
  {
    name: "Chop Bar",
    location: "190 4th St",
    yelpRating: 4.5,
    website: "https://www.oaklandchopbar.com/",
  },
  {
    name: "Beauty's Bagel Shop",
    location: "3838 Telegraph Ave",
    yelpRating: 4.5,
    website: "https://www.beautysbagelshop.com/",
  },
  {
    name: "Marica",
    location: "5301 College Ave",
    yelpRating: 4.5,
    website: "http://maricaoakland.com/",
  },
  {
    name: "Pizzaiolo",
    location: "5008 Telegraph Ave",
    yelpRating: 4.5,
    website: "http://www.pizzaiolooakland.com/",
  },
  {
    name: "Nido Kitchen & Bar",
    location: "444 Oak St",
    yelpRating: 4.5,
    website: "https://www.nidooakland.com/",
  },
  {
    name: "Hawker Fare",
    location: "2300 Webster St",
    yelpRating: 4.5,
    website: "http://www.hawkerfare.com/",
  },
  {
    name: "Cholita Linda",
    location: "4923 Telegraph Ave",
    yelpRating: 4.5,
    website: "https://cholitalinda.com/",
  },
  {
    name: "Zachary's Chicago Pizza",
    location: "5801 College Ave",
    yelpRating: 4.5,
    website: "https://zacharys.com/",
  },
  {
    name: "Anula's Cafe",
    location: "500 25th St",
    yelpRating: 4.5,
    website: "https://anulas.com/",
  },
  {
    name: "Everett & Jones Barbeque",
    location: "126 Broadway",
    yelpRating: 4.5,
    website: "https://www.eandjbbq.com/",
  },
  {
    name: "Tacos Mi Rancho",
    location: "1434 1st Ave",
    yelpRating: 4.5,
    website: "http://tacosmirancho.com/",
  },
  {
    name: "B-Dama",
    location: "4301 Piedmont Ave",
    yelpRating: 4.5,
    website: "https://b-dama.com/",
  },
  {
    name: "Nido",
    location: "444 Oak St",
    yelpRating: 4.5,
    website: "https://www.nidooakland.com/",
  },
  {
    name: "Zella's Soulful Kitchen",
    location: "4929 Shattuck Ave",
    yelpRating: 4.5,
    website: "http://zellaskitchen.com/",
  },
  {
    name: "Plum Bar & Restaurant",
    location: "2216 Broadway",
    yelpRating: 4.5,
    website: "https://plumbaroakland.com/",
  },
  {
    name: "Belly",
    location: "1901 San Pablo Ave",
    yelpRating: 4.5,
    website: "https://bellyuptown.com/",
  },
  {
    name: "Starline Social Club",
    location: "2236 Martin Luther King Jr Way",
    yelpRating: 4.5,
    website: "https://www.starlinesocialclub.com/",
  },
  {
    name: "Bocanova",
    location: "55 Webster St",
    yelpRating: 4.5,
    website: "http://www.bocanova.com/",
  },
  {
    name: "Mockingbird",
    location: "416 13th St",
    yelpRating: 4.5,
    website: "https://mockingbirdoakland.com/",
  },
  {
    name: "Duende",
    location: "468 19th St",
    yelpRating: 4.5,
    website: "https://www.duendeoakland.com/",
  },
  {
    name: "La Marcha",
    location: "2026 San Pablo Ave",
    yelpRating: 4.5,
    website: "https://www.lamarcha.com/",
  },
  {
    name: "Cafe Gabriela",
    location: "988 Broadway",
    yelpRating: 4.5,
    website: "https://www.cafegabriela.com/",
  },
  {
    name: "KronnerBurger",
    location: "4063 Piedmont Ave",
    yelpRating: 4.5,
    website: "https://www.kronnerburger.com/",
  },
  {
    name: "Forge Pizza",
    location: "66 Franklin St",
    yelpRating: 4.5,
    website: "https://www.theforgepizza.com/",
  },
  {
    name: "Navi Kitchen",
    location: "5000 Adeline St",
    yelpRating: 4.5,
    website: "https://www.navikitchen.com/",
  },
  {
    name: "Tamarindo Antojeria",
    location: "468 8th St",
    yelpRating: 4.5,
    website: "https://tamarindoantojeria.com/",
  },
  {
    name: "Angeline's Louisiana Kitchen",
    location: "2261 Shattuck Ave",
    yelpRating: 4.5,
    website: "https://www.angelineskitchen.com/",
  },
  {
    name: "Gogi Time",
    location: "2600 Telegraph Ave",
    yelpRating: 4.5,
    website: "https://gogitime.com/",
  },
  {
    name: "Nyum Bai",
    location: "3340 E 12th St",
    yelpRating: 4.5,
    website: "https://www.nyumbai.com/",
  },
  {
    name: "Noodle Theory Provisions",
    location: "6099 Claremont Ave",
    yelpRating: 4.5,
    website: "https://noodletheoryprovisions.com/",
  },
];
